version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  htpasswd:
    realm: home-docker-reg-realm
    path: /auth/htpasswd
http:
  addr: :5000
  tls:
    certificate: /run/secrets/tls.crt
    key: /run/secrets/tls.key
  headers:
    X-Content-Type-Options: [nosniff]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
