version: "3.5"
services:
  home-docker-reg:
    image: registry:2
    ports:
      - 6000:5000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.com.ferguslee.home.docker-registry == true
    secrets:
      - source: home-docker-reg.crt
        target: home-docker-reg.crt
      - source: home-docker-reg.key
        target: home-docker-reg.key
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/home-docker-reg.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/home-docker-reg.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Home Docker Reg Realm
    volumes:
      - home-docker-reg-data:/var/lib/registry
      - home-docker-reg-auth:/auth

volumes:
  home-docker-reg-data:
  home-docker-reg-auth:

secrets:
  home-docker-reg.crt:
    external: true
  home-docker-reg.key:
    external: true
