version: "3.5"
services:
  home-docker-reg:
    image: registry:2
    ports:
      - 6000:5000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.com.ferguslee.home.docker-registry == true
    configs:
      - source: config.yml
        target: /etc/docker/registry/config.yml
    secrets:
      - source: home-docker-reg_https.crt
        target: https.crt
      - source: home-docker-reg_https.key
        target: https.key
    volumes:
      - data:/var/lib/registry
      - auth:/auth

volumes:
  data:
  auth:

configs:
  config.yml:
    file: ./config.yml

secrets:
  home-docker-reg_https.crt:
    external: true
  home-docker-reg_https.key:
    external: true
